# .github/workflows/deploy-production.yaml
name: Deploy

on:
  release:
    types: [released]
jobs:
  release-production:
    name: Release to Production
    if: startsWith(github.ref_name, 'r-') # the prefix we have added to the tag
    environment: prod
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Mock
        run: |
          echo "Deploying to dev"
          echo "Deployed ${{ needs.build.outputs.image_version }} to dev"
