# .github/workflows/deploy-production.yaml
name: Production - Feature A
on:
  release:
    types: [released]
jobs:
  release-production:
    name: Release to Production
    environment: prod
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Mock
        run: |
          echo "Deploying to prod"
          echo "Deployed version \"${{ needs.build.outputs.image_version }}\" to prod"
