name: Semver Auto

on:
  workflow_dispatch:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Determine new version
        id: semantic-version
        uses: PaulHatch/semantic-version@v5.0.3
      - name: Create Release Link
        id: create_release_link
        run: echo "::set-output name=link::https://github.com/${{ github.repository }}/releases/new?tag=v${{ steps.semantic-version.outputs.new-version }}&target=${{ github.sha }}"
      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          # Slack channel id, channel name, or user id to post message.
          # See also: https://api.slack.com/methods/chat.postMessage#channels
          # You can pass in multiple channels to post to by providing a comma-delimited list of channel IDs.
          channel-id: "C05QJ8PBU0N"
          # For posting a simple plain text message
          slack-message: "The release link is ${{ steps.create_release_link.outputs.link }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
