name: semver

on:
  workflow_dispatch:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git Semantic Version
        uses: PaulHatch/semantic-version@v5.0.3
